version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build-debug-apk:
    executor:
      name: android/android_machine
      resource_class: medium
      tag: default
    steps:
      - checkout
      - accept_licenses
      - android/restore_build_cache:
          cache_prefix: devent-v1
      - name: Grant Execute Permissions
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Store Debug APK Artifact
        store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debug/debug-apk
      - android/save_build_cache:
          cache_prefix: devent-v1

workflows:
  android-workflow:
    jobs:
      - build-debug-apk
