version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    executor:
      name: android/android_machine
      resource_class: small
    steps:
      - checkout

workflows:
  android-workflow:
    jobs:
      - build
